### ISSUE TITLE
Link to this repo from your iJS 2021 talk?

### ISSUE THREAD

**Issue by AlexErrant** [rust-linz/rust-fundamentals-training#21]
Hi, thanks for a great talk here https://www.youtube.com/watch?v=zq4s3LAUz4A

I think that video's description could use a link to https://github.com/rust-linz/rust-fundamentals-training/tree/main/examples/110-wasm as it's mentioned around 24:30

Thanks again!

**Comment by rstropek** [comment]
Yes, it is the repo. Thank you for pointing that out. Video now has link to the code.
